[package]
name = "oclob-node"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
zeroize = { version = "1.8", features = ["alloc"] }
zkfmi-crypto = { workspace = true, features = ["tls"] }
oclob-core.workspace = true
oclob-dekyx.workspace = true
oclob-edge.workspace = true
oclob-mpc.workspace = true
oclob-ordering.workspace = true
oclob-settlement.workspace = true
ed25519-dalek.workspace = true
openssl.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
thiserror.workspace = true
qomm-zkpi.workspace = true
qomm-mpc.workspace = true
qomm-transport.workspace = true
qomm-defmi.workspace = true
qomm-proofs.workspace = true
qomm-zk.workspace = true
curve25519-dalek.workspace = true
zkpi-defmi-sdk.workspace = true
libc.workspace = true
tiny_http.workspace = true

[dev-dependencies]
